bot_channel = 'ctf-news'
data_uri = 'tests/ctfd.db'
db_uri = 'tests/ctfd.db'
emoji1 = 'dab'
emoji2 = 'ok_hand'
emoji3 = 'thinking'
emoji4 = 'thinking'
emoji5 = 'thumbsdown'
limit_size = 1000
medals = [':first_place:', ':second_place:', ':third_place:']
token = 'token'
